apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      name: todo-frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: todo-frontend
    spec:
      containers:
      - name: todo-frontend
        image: abinavram/todo
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    name: todo-frontend      
  ports:
  - name: todo-frontend-port
    port: 4200
    protocol: TCP
    nodePort: 31040
  type: LoadBalancer